import subprocess

def plan(planner_folder):
    """This function takes the new updated problem.pddl and the domain.pddl
        files and creates a plan for the robots to execute to obtain the 
        desired kit complement.

    Args:
        planner_folder ([str]): filepath to the folders for PDDL files

    Returns:
        moves ([list]): list of robot moves generated by the PDDL planner
    """

    # domain file
    domain_file = planner_folder + '/rwa2-domain.pddl'
    # problem file
    problem_file = planner_folder + '/rwa2-updated-problem.pddl'
    # planner binary to execute on domain and problem files
    planner = f'{planner_folder}/popf3-clp {domain_file} {problem_file}'

    # bash command execution from Python
    planner_cmd = ['bash', '-c', planner]
    process = subprocess.Popen(planner_cmd, stdout=subprocess.PIPE)

    moves = []
    for line in process.stdout:
        # print(line)
        if "b'0" in str(line):
            result = str(line)[str(line).find('(') + 1:str(line).find(')')]
            # print(result)
            moves.append(result)
    process.wait()

    # print(process.returncode)

    return moves
   

if __name__ == '__main__':

    # root directory of the planner
    # Note: Please indicate test file path before execution.
    
    # Shon's Test file path
    planner_folder = '/home/luna/Desktop/popf-tif-clp/planner/debug/popf'
    # Brenda's test file path
    # planner_folder = '/home/brenda/Desktop/popf-tif-clp/planner/debug/popf'
    # Souvik's test file path
    # planner_folder = '/home/souvik/Documents/ENPM809E/Resources/L8-Task_Level_Planning/popf-tif-clp/planner/debug/popf'
    

    plan(planner_folder)
